import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const cameraStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },

  // Loading Screen
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: "Kanit-Medium",
    color: "#6b7280",
  },

  // Success Screen
  successGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  successContent: {
    alignItems: "center",
    paddingHorizontal: 32,
  },
  successIcon: {
    marginBottom: 24,
  },
  successTitle: {
    fontSize: 24,
    fontFamily: "Kanit-Bold",
    color: "white",
    marginBottom: 16,
  },
  successAmount: {
    fontSize: 32,
    fontFamily: "Kanit-ExtraBold",
    color: "white",
    marginBottom: 8,
  },
  successDetails: {
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    color: "rgba(255, 255, 255, 0.9)",
    marginBottom: 40,
  },
  successButtonContainer: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
  },
  newScanButton: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "white",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  newScanText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
  },
  historyButton: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 25,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  historyText: {
    color: "#B46A07",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
  },

  // Clean Scanner
  cleanScannerContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  cleanCameraArea: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  processingOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -50 }, { translateY: -50 }],
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    padding: 24,
    borderRadius: 16,
  },
  processingText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-Medium",
    marginTop: 12,
  },
  cleanButtonContainer: {
    paddingBottom: 60,
    alignItems: "center",
  },
  cleanScanButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#B46A07",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B46A07",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  scanButtonDisabled: {
    backgroundColor: "#9ca3af",
    shadowColor: "#9ca3af",
    shadowOpacity: 0.2,
  },
  scanButtonText: {
    color: "#B46A07",
    fontSize: 14,
    fontFamily: "Kanit-SemiBold",
    marginTop: 8,
  },
  manualEntryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#B46A07",
    marginTop: 16,
    gap: 8,
  },
  manualEntryButtonText: {
    color: "#B46A07",
    fontSize: 14,
    fontFamily: "Kanit-SemiBold",
  },

  // Instructions Container
  instructionsContainer: {
    backgroundColor: "#ffffff",
    marginTop: 60,
    margin: 20,
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#f1f5f9",
  },
  instructionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  instructionsTitle: {
    fontSize: 20,
    fontFamily: "Kanit-Bold",
    color: "#1f2937",
    marginLeft: 12,
  },
  instructionsScrollView: {
    maxHeight: 200,
  },
  stepsList: {
    gap: 16,
  },
  instructionStep: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#B46A07",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  stepNumberText: {
    fontSize: 14,
    fontFamily: "Kanit-SemiBold",
    color: "white",
  },
  stepText: {
    flex: 1,
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    color: "#374151",
    lineHeight: 22,
  },
  quickTipsContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  quickTipsTitle: {
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
    color: "#6b7280",
    marginBottom: 12,
  },
  tipsList: {
    gap: 8,
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  tipText: {
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    color: "#6b7280",
    marginLeft: 8,
  },

  // Modern Food Delivery Style
  modernContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  modernHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  cancelFlowButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 16,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: "Kanit-Bold",
    color: "#1f2937",
    marginBottom: 4,
  },
  headerWeight: {
    fontSize: 14,
    fontFamily: "Kanit-Medium",
    color: "#6b7280",
  },
  modernScrollView: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  modernGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },

  // Improved fruit cards
  improvedFruitCard: {
    width: (width - 50) / 2,
    backgroundColor: "#ffffff",
    borderRadius: 24,
    marginBottom: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    minHeight: 180,
    alignItems: "center",
    justifyContent: "space-between",
  },
  fruitImageContainer: {
    alignItems: "center",
    marginBottom: 12,
  },
  improvedFruitEmoji: {
    fontSize: 64,
    marginBottom: 12,
  },
  improvedFruitInfo: {
    alignItems: "center",
    flex: 1,
  },
  improvedFruitName: {
    fontSize: 18,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
    marginBottom: 8,
    textAlign: "center",
    lineHeight: 24,
  },
  improvedFruitPrice: {
    fontSize: 16,
    color: "#B46A07",
    fontFamily: "Kanit-Bold",
    textAlign: "center",
    marginBottom: 12,
  },
  selectIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(180, 106, 7, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modernAddCard: {
    width: (width - 60) / 2,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#B46A07",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 160,
  },
  addIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(180, 106, 7, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  addFruitLabel: {
    fontSize: 14,
    fontFamily: "Kanit-SemiBold",
    color: "#B46A07",
    textAlign: "center",
    marginBottom: 4,
  },
  addFruitInfo: {
    alignItems: "center",
  },
  addFruitSubtext: {
    fontSize: 12,
    fontFamily: "Kanit-Regular",
    color: "#9ca3af",
    textAlign: "center",
  },
  emptyFruitsContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    width: "100%",
  },
  emptyFruitsText: {
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    color: "#9ca3af",
    marginTop: 12,
    textAlign: "center",
  },

  // Photo Confirmation
  confirmPhotoContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  confirmPhotoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    backgroundColor: "#ffffff",
  },
  confirmPhotoTitle: {
    fontSize: 18,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 16,
  },
  confirmPhotoAction: {
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
    color: "#B46A07",
  },
  disabledAction: {
    color: "#9ca3af",
  },
  photoContainer: {
    flex: 1,
    margin: 20,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#f8fafc",
    position: "relative",
  },
  capturedPhoto: {
    width: "100%",
    height: "100%",
  },
  cropOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  cropSuggestions: {
    position: "absolute",
    top: 20,
    left: 20,
    right: 20,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  suggestionText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
    textAlign: "center",
    marginBottom: 4,
  },
  suggestionSubtext: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    textAlign: "center",
  },
  cropSelectionBox: {
    position: "absolute",
    borderWidth: 3,
    borderColor: "#B46A07",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(180, 106, 7, 0.1)",
    borderStyle: "dashed",
    minWidth: 80,
    minHeight: 40,
  },
  cropCorner: {
    position: "absolute",
    width: 20,
    height: 20,
    borderWidth: 4,
    borderColor: "#B46A07",
    top: -4,
    left: -4,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    backgroundColor: "white",
  },
  topRight: {
    right: -4,
    left: "auto",
    borderLeftWidth: 0,
    borderRightWidth: 4,
  },
  bottomLeft: {
    bottom: -4,
    top: "auto",
    borderTopWidth: 0,
    borderBottomWidth: 4,
  },
  bottomRight: {
    bottom: -4,
    right: -4,
    top: "auto",
    left: "auto",
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  cropCenter: {
    alignItems: "center",
  },
  cropCenterText: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 14,
    fontFamily: "Kanit-Medium",
    marginTop: 8,
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  cropInstructions: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#f8fafc",
  },
  instructionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  instructionText: {
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    color: "#6b7280",
    marginLeft: 12,
    flex: 1,
  },
  confirmPhotoActions: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    backgroundColor: "#ffffff",
  },
  skipCropButton: {
    flex: 1,
    backgroundColor: "transparent",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  skipCropText: {
    color: "#6b7280",
    fontSize: 16,
    fontFamily: "Kanit-Medium",
  },
  processWithCropButton: {
    flex: 2,
    backgroundColor: "#B46A07",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  disabledButton: {
    backgroundColor: "#9ca3af",
  },
  processWithCropText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
  },

  // Weight Confirmation
  confirmContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  confirmHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
    paddingTop: 60,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  confirmTitle: {
    fontSize: 18,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
    marginLeft: 16,
  },
  orderSummary: {
    flex: 1,
    padding: 24,
  },
  fruitSummary: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  summaryEmoji: {
    fontSize: 48,
    marginRight: 16,
  },
  summaryDetails: {
    flex: 1,
  },
  summaryFruitName: {
    fontSize: 20,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
    marginBottom: 4,
  },
  summaryWeight: {
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    color: "#6b7280",
  },
  weightInputContainer: {
    marginTop: 4,
  },
  weightEditRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  weightInput: {
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
    borderBottomWidth: 2,
    borderBottomColor: "#B46A07",
    paddingVertical: 4,
    minWidth: 80,
  },
  weightUnit: {
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    color: "#6b7280",
  },
  weightDisplayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priceBreakdown: {
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 20,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  priceLabel: {
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    color: "#6b7280",
  },
  priceValue: {
    fontSize: 16,
    fontFamily: "Kanit-Medium",
    color: "#1f2937",
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 12,
    marginTop: 8,
    marginBottom: 0,
  },
  totalLabel: {
    fontSize: 18,
    fontFamily: "Kanit-SemiBold",
    color: "#1f2937",
  },
  totalPrice: {
    fontSize: 22,
    fontFamily: "Kanit-Bold",
    color: "#B46A07",
  },
  confirmButton: {
    margin: 24,
    backgroundColor: "#B46A07",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: "#B46A07",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
  },

  // Offline Notice
  offlineNotice: {
    backgroundColor: "#fef3c7",
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 20,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#fcd34d",
  },
  offlineTextContainer: {
    flex: 1,
  },
  offlineTitle: {
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
    color: "#92400e",
    marginBottom: 2,
  },
  offlineText: {
    fontSize: 14,
    fontFamily: "Kanit-Regular",
    color: "#b45309",
  },
  manualEntryButtonProminent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#B46A07",
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 24,
    marginTop: 16,
    gap: 8,
    shadowColor: "#B46A07",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  manualEntryButtonProminentText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Kanit-SemiBold",
  },
});
